languageCode: en-us
title: Example Site

params:
  mainSections:
    - posts
    - events
  #featuredImageField: image
  rssFullContent: true
  favicon: /images/icon/favicon.ico

  dateFormat:
    published: 2 Jan 2006
    lastUpdated: "2 Jan 2006"
    event: "2 Jan 2006, 15:04"
    eventEndShort: "15:04"

  events:
    organizer:
      name: CSSZ
      email: info@cssz.ch

  sidebar:
    compact: false
    #emoji: üç•
    subtitle:
    avatar:
      enabled: true
      local: true
      src: images/TEST_13_crop.png

  article:
    math: false
    toc: true
    readingTime: true
    license:
      enabled: false
      default: Licensed under CC BY-NC-SA 4.0

  comments:
    enabled: false
    #...

  widgets:
    homepage:
      - type: search
#      - type: archives
#        params:
#          limit: 5
#      - type: categories
#        params:
#          limit: 10
#      - type: tag-cloud
#        params:
#          limit: 10
      - type: partner_logos
        params:
          partners:
            - title: ETH
              logo: images/partners/eth.png
            - title: VSETH
              logo: images/partners/vseth_Logo_bylines_Kommission.png
            - title: Impuls Fabrik
              logo: images/partners/impuls.png

    page:
      - type: search
      - type: toc
      - type: partner_logos
        params:
          partners:
            - title: ETH
              logo: images/partners/eth.png
            - title: VSETH
              logo: images/partners/vseth_Logo_bylines_Kommission.png
            - title: Impuls Fabrik
              logo: images/partners/impuls.png

  opengraph:
    #twitter:
      # Your Twitter username
      #site:

      # Available values: summary, summary_large_image
      #card: summary_large_image

  defaultImage:
    opengraph:
      enabled: false
      local: false
      src:

  colorScheme:
    # Display toggle
    toggle: false

    # Available values: auto, light, dark
    default: light

  imageProcessing:
    cover:
      enabled: true
    content:
      enabled: true
    imageTypes:
      default:
        responsive_image_widths: [640, 1024, 1600, 2000, 4000] # at what sizes should images be generated
        max_vw: 100 # what is the maximum expected viewport width (100%). For smaller images, e.g. thumbnails, this will be smaller. responsiveImageWidths are then scaled appropriately.
        quality: 85
      thumbnail:
        width: 100
        height: 100
        loading: lazy
        max_vw: 10
      featured:
        width: 1253
        max_vw: 100
        quality: 85
        loading: lazy
      tile:
        width: 250
        height: 150
        quality: 75
        loading: lazy
      person:
        width: 180
        height: 180
        max_vw: 20

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
  #main: []

#  social:
#    - identifier: github
#      name: GitHub
#      url: https://github.com/CaiJimmy/hugo-theme-stack
#      params:
#        icon: brand-github
#
#    - identifier: twitter
#      name: Twitter
#      url: https://twitter.com
#      params:
#        icon: brand-twitter
